# Generated by Django 3.2.20 on 2023-08-07 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_restaurant', '0002_restaurant_event_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant_reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solo', models.BooleanField(default=True)),
                ('num_friends', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant_event',
            name='attendees',
        ),
        migrations.DeleteModel(
            name='restaurant_user',
        ),
        migrations.AddField(
            model_name='restaurant_reservation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_restaurant.restaurant_event'),
        ),
        migrations.AddField(
            model_name='restaurant_reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
