# Generated by Django 3.2.20 on 2023-08-09 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_restaurant', '0005_restaurant_event_available_spots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant_event',
            name='available_spots',
        ),
    ]
