# Generated by Django 3.2.20 on 2023-08-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_restaurant', '0006_remove_restaurant_event_available_spots'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_event',
            name='available_spots',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
