# Generated by Django 3.2.20 on 2023-08-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_restaurant', '0010_restaurant_event_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant_event',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='restaurant_event',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
