# Generated by Django 3.2.20 on 2023-08-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_restaurant', '0011_auto_20230812_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_event',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='image'),
        ),
    ]
